AllCops:
  NewCops: enable
Metrics/MethodLength:
  Max: 15
Naming/RescuedExceptionsVariableName:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
